[2024-11-21T11:48:55.869+0000] {processor.py:186} INFO - Started process (PID=49) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:48:55.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:48:55.882+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:48:55.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:48:56.276+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:48:56.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:48:56.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:48:56.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.477 seconds
[2024-11-21T11:49:26.923+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:49:26.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:49:26.932+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:49:26.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:49:30.398+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:49:30.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:49:30.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:49:30.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 3.578 seconds
[2024-11-21T11:50:01.686+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:50:01.687+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:50:01.688+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:50:01.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:50:02.079+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:50:02.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:50:02.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:50:02.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.409 seconds
[2024-11-21T11:50:32.209+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:50:32.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:50:32.217+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:50:32.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:50:32.549+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:50:32.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:50:32.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:50:32.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.362 seconds
[2024-11-21T11:51:02.709+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:51:02.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:51:02.715+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:51:02.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:51:03.204+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:51:03.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:51:03.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:51:03.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.517 seconds
[2024-11-21T11:51:33.578+0000] {processor.py:186} INFO - Started process (PID=369) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:51:33.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:51:33.582+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:51:33.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:51:33.671+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:51:33.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:51:33.671+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:51:33.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.109 seconds
[2024-11-21T11:52:03.731+0000] {processor.py:186} INFO - Started process (PID=433) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:52:03.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:52:03.734+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:52:03.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:52:03.798+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:52:03.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:52:03.799+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:52:03.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.081 seconds
[2024-11-21T11:52:34.491+0000] {processor.py:186} INFO - Started process (PID=496) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:52:34.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:52:34.498+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:52:34.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:52:34.587+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:52:34.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:52:34.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:52:34.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.118 seconds
[2024-11-21T11:53:05.256+0000] {processor.py:186} INFO - Started process (PID=560) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:53:05.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:53:05.259+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:53:05.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:53:05.343+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:53:05.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:53:05.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:53:05.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.112 seconds
[2024-11-21T11:53:36.028+0000] {processor.py:186} INFO - Started process (PID=624) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:53:36.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:53:36.031+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:53:36.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:53:36.132+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:53:36.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:53:36.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:53:36.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.120 seconds
[2024-11-21T11:54:10.419+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:54:10.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:54:14.117+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:54:13.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:54:19.562+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:54:19.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:54:19.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:54:19.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 9.350 seconds
[2024-11-21T11:55:05.568+0000] {processor.py:186} INFO - Started process (PID=778) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:55:05.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:55:05.661+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:55:05.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:55:06.806+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:55:06.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:55:06.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:55:12.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 7.731 seconds
[2024-11-21T11:55:43.015+0000] {processor.py:186} INFO - Started process (PID=843) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:55:43.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:55:43.023+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:55:43.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:55:43.356+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:55:43.348+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:55:43.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:55:43.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.396 seconds
[2024-11-21T11:56:17.475+0000] {processor.py:186} INFO - Started process (PID=875) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:56:17.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:56:17.496+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:56:17.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:56:18.720+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:56:18.666+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:56:18.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:56:19.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 1.623 seconds
[2024-11-21T11:56:49.121+0000] {processor.py:186} INFO - Started process (PID=940) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:56:49.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:56:49.123+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:56:49.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:56:49.236+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:56:49.232+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:56:49.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:56:49.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.132 seconds
[2024-11-21T11:57:20.044+0000] {processor.py:186} INFO - Started process (PID=1004) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:57:20.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:57:20.047+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:57:20.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:57:20.132+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:57:20.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:57:20.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:57:20.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.107 seconds
[2024-11-21T11:57:51.003+0000] {processor.py:186} INFO - Started process (PID=1068) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:57:51.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:57:51.014+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:57:51.013+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:57:51.224+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:57:51.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:57:51.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:57:51.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.274 seconds
[2024-11-21T11:58:21.761+0000] {processor.py:186} INFO - Started process (PID=1132) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:58:21.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:58:21.764+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:58:21.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:58:21.872+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:58:21.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:58:21.873+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:58:21.898+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.143 seconds
[2024-11-21T11:58:52.342+0000] {processor.py:186} INFO - Started process (PID=1196) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:58:52.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:58:52.346+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:58:52.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:58:52.445+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:58:52.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:58:52.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:58:52.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.121 seconds
[2024-11-21T11:59:23.144+0000] {processor.py:186} INFO - Started process (PID=1260) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:59:23.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:59:23.149+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:59:23.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:59:23.254+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:59:23.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:59:23.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:59:23.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.133 seconds
[2024-11-21T11:59:54.058+0000] {processor.py:186} INFO - Started process (PID=1325) to work on /opt/airflow/dags/minio.py
[2024-11-21T11:59:54.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T11:59:54.062+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:59:54.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T11:59:54.180+0000] {logging_mixin.py:190} INFO - [2024-11-21T11:59:54.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T11:59:54.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T11:59:54.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.144 seconds
[2024-11-21T12:02:04.696+0000] {processor.py:186} INFO - Started process (PID=1384) to work on /opt/airflow/dags/minio.py
[2024-11-21T12:02:04.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T12:02:04.718+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:02:04.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T12:02:05.195+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:02:05.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T12:02:05.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T12:02:05.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.633 seconds
[2024-11-21T12:04:01.111+0000] {processor.py:186} INFO - Started process (PID=1461) to work on /opt/airflow/dags/minio.py
[2024-11-21T12:04:01.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T12:04:01.118+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:04:01.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T12:04:01.307+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:04:01.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T12:04:01.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T12:04:01.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.248 seconds
[2024-11-21T12:26:19.736+0000] {processor.py:186} INFO - Started process (PID=1503) to work on /opt/airflow/dags/minio.py
[2024-11-21T12:26:19.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T12:26:19.780+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:26:19.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T12:26:20.791+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:26:20.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T12:26:20.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T12:26:21.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 1.548 seconds
[2024-11-21T12:43:07.760+0000] {processor.py:186} INFO - Started process (PID=1556) to work on /opt/airflow/dags/minio.py
[2024-11-21T12:43:07.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T12:43:07.773+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:43:07.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T12:43:08.397+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:43:08.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T12:43:08.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T12:43:08.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 0.756 seconds
[2024-11-21T12:54:08.999+0000] {processor.py:186} INFO - Started process (PID=1594) to work on /opt/airflow/dags/minio.py
[2024-11-21T12:54:09.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T12:54:09.279+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:54:09.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T12:54:13.677+0000] {logging_mixin.py:190} INFO - [2024-11-21T12:54:13.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T12:54:13.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T12:54:18.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 10.353 seconds
[2024-11-21T13:37:00.249+0000] {processor.py:186} INFO - Started process (PID=1717) to work on /opt/airflow/dags/minio.py
[2024-11-21T13:37:00.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T13:37:00.263+0000] {logging_mixin.py:190} INFO - [2024-11-21T13:37:00.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T13:37:01.651+0000] {logging_mixin.py:190} INFO - [2024-11-21T13:37:01.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T13:37:01.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T13:37:01.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 1.594 seconds
[2024-11-21T14:33:49.949+0000] {processor.py:186} INFO - Started process (PID=1786) to work on /opt/airflow/dags/minio.py
[2024-11-21T14:33:49.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/minio.py for tasks to queue
[2024-11-21T14:33:50.082+0000] {logging_mixin.py:190} INFO - [2024-11-21T14:33:50.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/minio.py
[2024-11-21T14:33:52.918+0000] {logging_mixin.py:190} INFO - [2024-11-21T14:33:52.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/minio.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/minio.py", line 53, in <module>
    with DAG(dag_id='Grab NYC Data to Minio',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Grab NYC Data to Minio' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-11-21T14:33:52.924+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/minio.py
[2024-11-21T14:33:53.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/minio.py took 3.558 seconds
